apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mern-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/mernstack
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern-stack
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend
