apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mern-stack
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
